# See: https://docs.codecov.io/docs/codecov-yaml
coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%
