FROM python:3.10-slim

# Install uv:0.5.1
COPY --from=ghcr.io/astral-sh/uv:0.5.1 /uv /uvx /bin/

# Change the working directory to 'app'
WORKDIR /app

# Copy project files and lock file
COPY pyproject.toml uv.lock ./
COPY . .

# Install project and dependencies
RUN pip install --upgrade pip \
 && pip install . --no-cache-dir
