FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

# Install uv:0.5.1
COPY --from=ghcr.io/astral-sh/uv:0.5.1 /uv /uvx /bin/

# Change the working directory to 'app'
WORKDIR /app

# Copy project files and lock file
COPY pyproject.toml uv.lock ./
COPY . .

# Install project and dependencies
RUN pip install --upgrade pip \
 && pip install . --no-cache-dir

RUN --mount=type=cache,target=/root/.cache/pip \
   pip uninstall -y typing_extensions && \
   pip install typing_extensions==4.11.0
