name: Integration Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  schedule:
    - cron: "30 6 * * 1"  # every Monday at 6:30 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests-slurm:
    name: Integration testing on a SLURM cluster
    runs-on: self-hosted
    timeout-minutes: 60
    if: github.actor == 'jacob-chmura' || github.actor == 'shenyanghuang'
    env:
      TGM_CI_LOG_BASE: $SLURM_TMPDIR/tgm_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install dependencies
        run: uv sync --group examples

      - name: Run Integration Tests
        run: uv run pytest -m "integration" -n auto -vvv

      - name: Get Latest CI Run Log Path
        if: always()
        id: get-log-dir
        run: |
          # Parse path + ID written by the test runner (2 lines in ~/tgm_ci/latest_path.txt)
          mapfile -t lines < "$TGM_CI_LOG_BASE/latest_path.txt"
          LOG_PATH="${lines[0]}"
          CI_RUN_DIR="${lines[1]}"

          echo "log_path=$LOG_PATH" >> "$GITHUB_OUTPUT"
          echo "ci_run_dir=$CI_RUN_DIR" >> "$GITHUB_OUTPUT"
          echo "Resolved log path: $LOG_PATH"
          echo "Resolved run dir: $CI_RUN_DIR"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-log-dir.outputs.ci_run_dir }}
          path: |
                ${{ steps.get-log-dir.outputs.log_path }}/*.out
                ${{ steps.get-log-dir.outputs.log_path }}/*.err

      - name: Minimize uv cache
        run: uv cache prune --ci
