name: Publish Python Package

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      release:
        description: "Set to 1 to publish to PyPI (leave blank for TestPyPI)"
        required: false
        default: "0"

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    # Require a v* tag and manual trigger
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag'
    environment: pypi
    permissions:
      id-token: write  # Required for PyPI Trusted Publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Check package metadata
        run: uv version

      - name: Build the package
        run: uv build

      - name: Sanity check that package installs and imports
        run: |
          echo "Verifying package installs and imports correctly..."
          uv run --with py-tgm --no-project -- python -c "import tgm; print(tgm.__version__)"

      - name: Publish to PyPI or TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: >-
            ${{ github.event.inputs.release == '1' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
