name: Spellcheck Action

on:  # yamllint disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run spellcheck
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .github/config/.codespellignore
          only_warn: 1
